site_name: pypi-example
site_url: https://pypi-example.readthedocs.io
site_description: A sample project that exists for PyPUG's "Tutorial on Packaging and Distributing Projects"
site_author: district10

repo_url: https://github.com/cubao/pypi-example
edit_uri: blob/main/docs/

theme: readthedocs
nav:
    - Home: index.md
    - Usage: usage.md
    - About:
        - Release Notes: about/release-notes.md
        - License: about/license.md
plugins:
  - include-markdown
copyright: Copyright &copy; 2023 <a href="https://github.com/cubao">cubao team</a>.
